<?xml version="1.0" encoding="UTF-8"?>
<<<<<<< HEAD
<testng-results skipped="0" failed="4" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="617" started-at="2015-05-15T10:07:09Z" finished-at="2015-05-15T10:07:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="617" started-at="2015-05-15T10:07:09Z" finished-at="2015-05-15T10:07:10Z">
      <class name="FrontendTesting.PageControllerTesting">
        <test-method status="PASS" signature="setUp()[pri:0, instance:FrontendTesting.PageControllerTesting@3cfbc9c9]" name="setUp" is-config="true" duration-ms="61" started-at="2015-05-15T12:07:09Z" finished-at="2015-05-15T12:07:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="CreateMyTimelinePost(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:FrontendTesting.PageControllerTesting@3cfbc9c9]" name="CreateMyTimelinePost" duration-ms="57" started-at="2015-05-15T12:07:09Z" data-provider="CreatePagePost" finished-at="2015-05-15T12:07:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Failed]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[welcome]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[public]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Sw]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed expected:<n> but was:<OK>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed expected:<n> but was:<OK>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at FrontendTesting.PageControllerTesting.CreateMyTimelinePost(PageControllerTesting.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateMyTimelinePost -->
        <test-method status="FAIL" signature="CreateMyTimelinePost(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:FrontendTesting.PageControllerTesting@3cfbc9c9]" name="CreateMyTimelinePost" duration-ms="21" started-at="2015-05-15T12:07:09Z" data-provider="CreatePagePost" finished-at="2015-05-15T12:07:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Ok]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[DW]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[custom(n,m)]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[SWII project]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ok expected:<n> but was:<OK>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ok expected:<n> but was:<OK>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at FrontendTesting.PageControllerTesting.CreateMyTimelinePost(PageControllerTesting.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateMyTimelinePost -->
        <test-method status="FAIL" signature="CreatePage(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:FrontendTesting.PageControllerTesting@3cfbc9c9]" name="CreatePage" duration-ms="31" started-at="2015-05-15T12:07:09Z" data-provider="CreatePage" finished-at="2015-05-15T12:07:09Z">
=======
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="3893" started-at="2015-05-14T17:33:04Z" finished-at="2015-05-14T17:33:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="3893" started-at="2015-05-14T17:33:04Z" finished-at="2015-05-14T17:33:08Z">
      <class name="FrontendTesting.PageControllerTesting">
        <test-method status="PASS" signature="setUp()[pri:0, instance:FrontendTesting.PageControllerTesting@4276f4a9]" name="setUp" is-config="true" duration-ms="47" started-at="2015-05-14T17:33:04Z" finished-at="2015-05-14T17:33:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="CreatePage(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:FrontendTesting.PageControllerTesting@4276f4a9]" name="CreatePage" duration-ms="3799" started-at="2015-05-14T17:33:04Z" data-provider="CreatePage" finished-at="2015-05-14T17:33:08Z">
>>>>>>> b4bce9d46968d253f312331916dbea989824bfcd
          <params>
            <param index="0">
              <value>
                <![CDATA[OK]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[AI]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[science]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Education]]>
              </value>
            </param>
          </params>
<<<<<<< HEAD
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[OK expected:<mai> but was:<OK>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: OK expected:<mai> but was:<OK>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at FrontendTesting.PageControllerTesting.CreatePage(PageControllerTesting.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreatePage -->
        <test-method status="FAIL" signature="CreatePage(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:FrontendTesting.PageControllerTesting@3cfbc9c9]" name="CreatePage" duration-ms="35" started-at="2015-05-15T12:07:09Z" data-provider="CreatePage" finished-at="2015-05-15T12:07:10Z">
=======
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreatePage -->
        <test-method status="FAIL" signature="CreatePage(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:FrontendTesting.PageControllerTesting@4276f4a9]" name="CreatePage" duration-ms="15" started-at="2015-05-14T17:33:08Z" data-provider="CreatePage" finished-at="2015-05-14T17:33:08Z">
>>>>>>> b4bce9d46968d253f312331916dbea989824bfcd
          <params>
            <param index="0">
              <value>
                <![CDATA[Failed]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[DW]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Education]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
<<<<<<< HEAD
              <![CDATA[Failed expected:<mai> but was:<OK>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed expected:<mai> but was:<OK>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at FrontendTesting.PageControllerTesting.CreatePage(PageControllerTesting.java:99)
=======
              <![CDATA[expected [OK] but found [Failed]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [OK] but found [Failed]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at FrontendTesting.PageControllerTesting.CreatePage(PageControllerTesting.java:75)
>>>>>>> b4bce9d46968d253f312331916dbea989824bfcd
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreatePage -->
<<<<<<< HEAD
        <test-method status="PASS" signature="tearDown()[pri:0, instance:FrontendTesting.PageControllerTesting@3cfbc9c9]" name="tearDown" is-config="true" duration-ms="373" started-at="2015-05-15T12:07:10Z" finished-at="2015-05-15T12:07:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
=======
>>>>>>> b4bce9d46968d253f312331916dbea989824bfcd
      </class> <!-- FrontendTesting.PageControllerTesting -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
